#+TITLE: org-extras layer

* Table of Contents                                       :TOC_4_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
- [[#key-bindings][Key bindings]]

* Description
This layer adds extra support for =org-mode=.

** Features:
  - Custom =org-latex= export functionality.
    - Float placement options for src blocks (e.g. listings) are now used.
    - Optional =tcolorbox= listings environment wrapper for minted.
      - Set the variable =org-latex-listings-wrapper= to ='tcolorbox= to enable.
      - =tcolorbox= options can be set using =org-latex-tcolorbox-default-options=, and
        a custom name for the =tcolorbox= environment can be set using the option =listings-env-name=
        in an =ATTR_LATEX= header.
  - Additional =projectile= settings.
    - Prefix =org-babel= sessions with the project name from =projectile=.
  - Echo sent Python code in the inferior shell via =org-babel=.
  - =ob-ipython= interaction and output adjustments
    - =:results value= output operates mostly as expected (e.g. without the shell prompt included).
  - Add all projects' todos to =org-agenda=.
  - Override =org-ref= settings to use org options for =#+BIBLIOGRAPHY= and =#+BIBLIOGRAPHYSTYLE=.
    - The bibliography block is printed in the location of the last =#+BIBLIOGRAPHY=.
  - Syntax highlighting for inline src statements (i.e. =src_<lang>[...]{...}=).
    - Support for non-breaking text fill (e.g. =fill-region=) of inline src statements.
  - =:no_title:= tag removes appearance/name of headlines

* Install
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =org-extras= to the existing =dotspacemacs-configuration-layers= list in this
file.

* Key bindings

| Key Binding | Description                                                        |
|-------------+--------------------------------------------------------------------|
| ~SPC , b h~ | Execute the source blocks from the current section backward        |
| ~SPC , b D~ | Remove source block output for block at point (or all with prefix) |
